# Generated by Django 2.2.11 on 2021-03-15 11:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('amount', models.IntegerField()),
                ('delivery_address_district', models.CharField(max_length=255)),
                ('delivery_address_indication', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money')], max_length=255)),
            ],
            options={
                'db_table': '"tokpa"."order"',
            },
        ),
    ]
