# Generated by Django 2.2.11 on 2021-03-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210316_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_details',
        ),
    ]
